using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectEulerSolutions.Lists
{
    public class SolutionList
    {
        private List<string> _solutionNames { get; }
        private List<string> _description { get; }

        public SolutionList()
        {
        }

        private void setNames()
        {
            _solutionNames.Add("Solution One");
            _solutionNames.Add("Solution Two");
        }

        private void setDesciptions()
        {
            _description.Add("Find the sum of multiples of 3 and 5 below 1000");            
            _description.Add("Each new term in the Fibonacci sequence is generated by adding the previous two terms. Find whose values do not exceed four million, find the sum of the even-valued terms");
        }

    }
}